CREATE DATABASE PROYECTO

CREATE TABLE Paquete(
	Codigo VARCHAR(8) NOT NULL,
	Direccion VARCHAR(20) NOT NULL,
	Peso REAL NOT NULL,
	Destinatario VARCHAR(20) NOT NULL,
	--fecha envio
	--tipo envio
	CONSTRAINT PK_COD PRIMARY KEY (Codigo),
	CONSTRAINT CHK_COD CHECK (Codigo LIKE '[A-Z][A-Z]_[0-9][0-9][0-9][0-9][0-9]'),
	CONSTRAINT CHK_PESO CHECK (Peso BETWEEN 0 AND 2)
	--constrain fecha
);

CREATE TABLE Rutas(
	ID_Ruta INT NOT NULL,
	Nombre VARCHAR(20) NOT NULL,
	CONSTRAINT PK_RUTA PRIMARY KEY (ID_Ruta)
);

CREATE TABLE C_Local(
	Codigo_Local INT NOT NULL,
	Nombre VARCHAR(20),
	CONSTRAINT PK_COD_LOCAL PRIMARY KEY (Codigo_Local)
);

CREATE TABLE Internacional(
	Codigo VARCHAR(8) NOT NULL,
	Linea_Aerea VARCHAR(20) NOT NULL DEFAULT 'Mexicana',
	Codigo_Local INT NOT NULL,
	Fecha_Entrega DATE DEFAULT GETDATE(),
	CONSTRAINT FK_COD_INT FOREIGN KEY (Codigo) REFERENCES Paquete(Codigo)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	CONSTRAINT FK_COD_LOCAL FOREIGN KEY (Codigo_Local) REFERENCES C_Local(Codigo_Local)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	CONSTRAINT CHK_FECHA CHECK(Fecha_Entrega BETWEEN '10/12/2020' AND GETDATE())
);

CREATE TABLE Conductor(
	RFC VARCHAR(13) NOT NULL,
	Nombre VARCHAR (20) NOT NULL,
	Direccion VARCHAR (20) NOT NULL,
	ID_Ruta INT NOT NULL
	CONSTRAINT PK_RFC PRIMARY KEY (RFC)
	CONSTRAINT FK_RUT_CON FOREIGN KEY (ID_Ruta) REFERENCES Rutas (ID_Ruta)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	CONSTRAINT CHK_ID_RUTA CHECK (ID_Ruta IN ('54','55','56','57')),
	CONSTRAINT CHK_CONDUCE CHECK (RFC LIKE '[A-Z][A-Z][A-Z][A-Z][0-9][0-9][0-9][0-9][0-9][0-9][0-9|A-Z][0-9|A-Z][0-9|A-Z]')
);

CREATE TABLE Nacional(
	Codigo VARCHAR(8) NOT NULL,
	Ciudad_Destino VARCHAR(30),
	RFC VARCHAR(13) NOT NULL,
	ID_Ruta INT NOT NULL,
	CONSTRAINT FK_COD_NAC FOREIGN KEY (Codigo) REFERENCES Paquete(Codigo)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	CONSTRAINT FK_CON_NAC FOREIGN KEY (RFC) REFERENCES Conductor(RFC)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	CONSTRAINT FK_RUT_NAC FOREIGN KEY (ID_Ruta) REFERENCES Rutas(ID_Ruta),
	CONSTRAINT CHK_IDRUTA CHECK (ID_Ruta IN ('54','55','56','57'))
);

CREATE TABLE Camion(
	Placa VARCHAR(7) NOT NULL,
	Carga_MAX INT,
	Ciudad_Resguardo VARCHAR (11) NOT NULL,
	CONSTRAINT PK_PLACA PRIMARY KEY (Placa),
	CONSTRAINT CHK_PLACA CHECK (Placa LIKE '[0-9][0-9][0-9]-[A-Z][A-Z][A-Z]'),
	CONSTRAINT CHK_CIUDAD CHECK (Ciudad_Resguardo IN ('CDMX','Monterrey','Guadalajara','Merida','Tijuana')),
	CONSTRAINT CHK_CARGA CHECK (Carga_MAX BETWEEN 0 AND 4000)
);

CREATE TABLE Conductor_Camion(
	RFC VARCHAR(13) NOT NULL,
	Placa VARCHAR(7) NOT NULL,
	Fecha DATE DEFAULT GETDATE(),
	CONSTRAINT CONDUCE_PK PRIMARY KEY (RFC, Placa),
	CONSTRAINT FK_PLACA FOREIGN KEY (Placa) REFERENCES Camion (Placa)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	CONSTRAINT CONDUCTORC_FK FOREIGN KEY (RFC) REFERENCES Conductor (RFC)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	CONSTRAINT CHK_FECHAC CHECK(Fecha BETWEEN '10/12/2020' AND GETDATE())
);